version: "3.4"

services:
  dev:
    image: golang:1.13.0-buster
    volumes:
      - .:/work
      - redisproto-mod:/go/pkg/mod/
    working_dir: /work
    command: bash
    environment:
      GO111MODULE: "on"

volumes:
  redisproto-mod: ~
